# tasks file for aws-vpc-role
---
- name: create a VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    dns_hostnames: "{{ dns_hostnames | default(true) }}"
    dns_support: "{{ dns_support | default(true) }}"
    region: "{{ aws_region }}"
    state: "{{ aws_state }}"
    tenancy: "{{ tenancy | default(default) }}"
  register: vpc_create
  retries: 5

- name: Debug the vpc details
  ansible.builtin.debug:
    var: vpc_create
    verbosity: 2

- name: Define a new Variable for the for the VPC_ID reference
  ansible.builtin.set_fact:
    vpc_create_id: "{{ vpc_create.id }}"
    vpc_create_name: "{{ vpc_create.name }}"